<aside id="aside" class="extended">
    <section class="sect sect__aside-top">
       <div class="sign">
            <img src="imgs/eat.svg" class="img__eat" width="120px" height="40px" />
            <em class="bolt"></em>
            <em class="bolt"></em>
       </div>
       <div class="sign sign-here">HERE
          <em class="hinge"></em>
         <em class="hinge"></em>
          <img src="imgs/arrowEat.svg"  width="51px" height="46px" />
       </div>
    </section>
    <section class="sect sect__aside-menu" id="aside_menu">
    </section>
    <a href="javascript:void(0)"  id="hamburger" class="hamburger"></a>
</aside>


<script type="text/javascript" defer src="js/aside.js"></script>
<script type="text/javascript" defer src="js/getRestaurants.js"></script>
